version: "3"

services:
  angus:
    build: .
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: python angus.py --daemon

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./templates:/app/templates
    env_file:
      - .env
    ports:
      - "8080:5000"
      
  angus_coral:
    build:
      context: .
      dockerfile: Dockerfile.coral
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - CORAL_SERVER_URL=https://coral.pushcollective.club/sse
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - angus
